### ISSUE TITLE
Show help when no arguments specified

### ISSUE THREAD

**Issue by MatthewJA** [GeoscienceAustralia/dea-conflux#20]
Behaviour:

```$ dea-conflux run-one
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jovyan/dea-conflux/dea_conflux/__main__.py", line 680, in <module>
    main()
  File "/env/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/env/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/env/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/env/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/env/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/jovyan/dea-conflux/dea_conflux/__main__.py", line 250, in run_one
    plugin = run_plugin(plugin)
  File "/home/jovyan/dea-conflux/dea_conflux/__main__.py", line 146, in run_plugin
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 553, in module_from_spec
AttributeError: 'NoneType' object has no attribute 'loader'
```

Expected behaviour:

```$ dea-conflux run-one
Usage: python -m dea_conflux run-one [OPTIONS]

  Run dea-conflux on one scene.

Options:
  -p, --plugin FILE           Path to Conflux plugin (.py).
  -i, --uuid TEXT             ID of scene to process.
  -s, --shapefile PATH        REQUIRED. Path to the polygon shapefile to run
                              polygon drill on.
  -o, --output PATH           REQUIRED. Path to the output directory.
  --partial / --no-partial    Include polygons that only partially intersect
                              the scene.
  --overedge / --no-overedge  Include data from over the scene boundary.
  -v, --verbose               [x>=0]
  --help                      Show this message and exit.
```

**Comment by omad** [comment]
From https://stackoverflow.com/questions/50442401/how-to-set-the-default-option-as-h-for-python-click/63566351#63566351

> As of version 7.1, one can simply specify `@click.command(no_args_is_help=True)`.
